alias agi="sudo apt-get install"
alias agu="sudo apt-get upgrade"
alias agup="sudo apt-get update"
alias acs="apt-cache search"
alias aar="sudo add-apt-repository"
alias pcs="pacaur -S"
alias pcss="pacaur -Ss"
alias pcsy="pacaur -Sy"
alias pcsyy="pacaur -Syy"
alias pcsyu="pacaur -Syu"
alais pcscc="pacaur -Scc" # clear package cache for uninstalled packages
alias sshnone="ssh -oNoneSwitch=yes -oNoneEnabled=yes"
alias scpnone="scp -oNoneSwitch=yes -oNoneEnabled=yes"
alias rsyncnone="rsync -e 'ssh -oNoneSwitch=yes -oNoneEnabled=yes'"
alias info="info --vi-keys"
